language: node_js
node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

# before_install:
#   - npm install -g codecov

script:
  - npm test -- --coverage

# after_success:
  # - codecov --token=5698eb11-48c7-4409-b11e-53d0f07a03a5
