export { default as Button } from './Button';
export { default as Email } from './Email';
export { default as Header } from './Header';
export { default as Instafeed } from './Instafeed';
export { default as Input } from './Input';
export { default as Navbar } from './Navbar';
export { default as P } from './P';
export { default as TitleText } from './TitleText';
export { default as UnderlineText } from './UnderlineText';
